### ISSUE TITLE
Downloading from Musicbed.com doesn't work

### ISSUE THREAD

**Issue by becauseim** [Miserlou/SoundScrape#163]
Downloading from SoundCloud works in proper way.

**Comment by brachna** [comment]
So the reason why it doesn't work now is because they force redirect logged user to profile completion page.
In order for it to go away one has to complete his profile. I have no idea of other ways to make it go away.
I completed 2 profiles we use in SoundScrape by default, so the error should not exist for them.
As for custom profiles - I'm making a small PR to notify user that he should complete his profile in case it's not completed.

**Comment by becauseim** [comment]
It seems that it doesn't work again. Or this problem appears only to me?

**Comment by brachna** [comment]
Works fine here.

**Comment by becauseim** [comment]
Downloading from Musicbed.com doesn't work again. Could you update the script?

**Comment by brachna** [comment]
Even if I fix it, I doubt PR will make it through...

**Comment by becauseim** [comment]
Thank! I hope that you will fix this.

**Comment by becauseim** [comment]
for example, not all the **_Hammock's_** tracks are available for download on the [Bandcamp](http://shop.hammockmusic.com/album/mysterium), while on [Musicbed](https://www.musicbed.com/albums/mysterium/3453) are available

**Comment by SimplicityGuy** [comment]
While MusicBed support is in there, it's very experimental and dependent on scraping. As with some other services, this code will likely get pulled if it's not working.
