### ISSUE TITLE
Music keeps being redownloaded

### ISSUE THREAD

**Issue by Starfox64** [Miserlou/SoundScrape#185]
There is a specific music in my SoundCloud library that gets downloaded everytime I run soundscrape on my liked tracks.

Here is the music in question: https://soundcloud.com/ed-harrison/footprint

**Comment by gamemasta0** [comment]
It appears that that's because it's a .wav file. I've made a pull request that includes code that fixes this problem. Prior to my changes, the code was only checking for <track_name>.mp3 before determining whether or not to download/overwrite a file. I added a check for <track_name>.wav. I've tested on my local copy and the track in question does not redownload with my changes. Here is the pull request I mentioned: https://github.com/Miserlou/SoundScrape/pull/179

**Comment by SimplicityGuy** [comment]
This issue is addressed in a future PR, after #241 is merged.
