### ISSUE TITLE
Custom Folder Pathing

### ISSUE THREAD

**Issue by spencerthayer** [Miserlou/SoundScrape#201]
Is it possible to customize folder paths from `./ARTIST_NAME - ALBUM_NAME/SONG_NUMBER - SONG_TITLE.mp3` to something like `./ARTIST_NAME/ALBUM_NAME - SONG_NUMBER - SONG_TITLE.mp3`?

**Comment by bourdeau** [comment]
I just discovered SoundScrape like 15min ago, but I'm digging into the code and it's hard coded, so unless you fork it and change it, it doesn't seem possible out the box. At least there is not option in the parser to set an expression to do so.

**Comment by spencerthayer** [comment]
Do you remember what line number the path is it specified in?

**Comment by SimplicityGuy** [comment]
There are some options here. You can provide the destination directory to place files. Within that destination directory, you can use the artist name provided by SoundCloud to create a sub-directory and place files there. What you're suggesting is providing more robust naming schemes. That's a nice feature request, but it's a bit out of scope of this tool. There are many other tools for taking files and allowing you to do bulk renaming. This type of functionality is better left to those tools rather than bloating the code here.
