### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 0x1d00ffff** [Miserlou/SoundScrape#222]
Running `python3.6.exe ~\repos\SoundScrape\soundscrape\soundscrape.py twofeetmusic` on Windows 10 results in

        Active code page: 65001
        Expecting value: line 1 column 1 (char 0)

Apparently [this](https://github.com/Miserlou/SoundScrape/blob/efc63b99ce7e78b352e2ba22d5e51f83445546d7/soundscrape/soundscrape.py#L272) call to `get_soundcloud_api2_data(artist_id)` fails because the `requests.get(v2_url)` call returns a 401 unauthorized error. Unfortunately I don't know enough to debug the issue further.

**Comment by iam-mhaseeb** [comment]
Facing same issue

**Comment by canihavesomecoffee** [comment]
It's happening with more and more artists for me. Some are fine, others... Forget about it.

This error can pop up for various reasons:
- `get_soundcloud_api_playlist_data`: This uses a hardcoded client token. If you use a different token, the issue is resolved
- `get_soundcloud_api2_data`: uses the `AGGRESSIVE_CLIENT_ID`. This one is also shared by multiple different repo's, and could, just like the main token, hit the daily usage, or be revoked. This seems to be the case as well.

See #203

**Comment by SimplicityGuy** [comment]
There is better http error handling in #241. Also, as the previous comment mentions, there are some issues with location or client ids.
