### ISSUE TITLE
 HTTPError: 401 Client Error

### ISSUE THREAD

**Issue by nicktabc** [Miserlou/SoundScrape#224]
![image](https://user-images.githubusercontent.com/47339591/52244684-a5b92f00-28d6-11e9-9ed1-7f0fdf65d380.png)

Hey i'm getting an error HTTPError: 401 Client Error

Occurs when downloading an artist's tracks. after a dozen or so tracks i receive this error. i can then enter the URL of the track in question and it downloads fine. and continue downloading the remainder of the artist's tracks until the same error pops up again.

**Comment by Gwimm** [comment]
yup
here too
![img](https://ptpb.pw/dtnL.png)

**Comment by Lanchon** [comment]
FYI, it's very poor etiquette to paste screenshots instead of their textual content. the developer can't copy as needed and that could mean great pain. and the whole thing is not searchable so you increase the chances that the next person with the same problem will end up posting a new issue, inconveniencing the developer further.

**Comment by JohnTravolski** [comment]
I am also having this exact problem. Has there been a solution?

**Comment by SimplicityGuy** [comment]
Better http error handling exists in #214. While that may not solve the problem at least the error is handled more gracefully.
