### ISSUE TITLE
path setting where downloads should be saved

### ISSUE THREAD

**Issue by tivoo** [Miserlou/SoundScrape#238]
So I am trying to set a custom path to download the files in, but it returns an error somehow:

`(base) MacBook-Pro-van-Timo:~ tivoo$ soundscrape -p Users/tivoo/Music/DJ MUSIC`
`Problem downloading [404]: Item Not Found`

Same for:

`(base) MacBook-Pro-van-Timo:~ tivoo$ soundscrape --path Users/tivoo/Music/DJ MUSIC`
`Problem downloading [404]: Item Not Found`

What am I not seeing?

**Comment by 11k** [comment]
Does it work if you don't specify a custom path? The `404` makes me think it's an issue with the URL.

**Comment by jamesg311** [comment]
Having similar issue here, though instead of 404, I get this error:

soundscrape -p /Users/James/Downloads
soundscrape: error: Please supply an artist's username or URL!

also tried:
soundscrape -p Users/James/Downloads
soundscrape -p /Volumes/Macintosh\ HD/Users/James/Downloads
soundscrape -p Volumes/Macintosh\ HD/Users/James/Downloads

All give an error.

**Comment by SimplicityGuy** [comment]
You need to specify a username from SoundCloud, for example:
```bash
soundscrape kapslap -p /Users/James/Downloads
```
or
```bash
soundscrape https://soundcloud.com/kapslap -p /Users/James/Downloads
```

**Comment by jamesg311** [comment]
Is it possible to set it as a default? Or do I need to set it as that path each time?

**Comment by SimplicityGuy** [comment]
> Is it possible to set it as a default? Or do I need to set it as that path each time?

You need to set that each time. There is a default, which is the current directory you're running this from.
