### ISSUE TITLE
[feature] Mixcloud support ?

### ISSUE THREAD

**Issue by benborges** [Miserlou/SoundScrape#25]
Wondering if current SoundScrape support Mixcloud ?
and if not..is there a plan to add it like the bandcamp option ?

**Comment by Miserlou** [comment]
No plans to support Mixcloud right now simply because I don't use it myself, but I'm very open to the suggestion. 

What's a good Mixcloud page I should check out? I like heavy and fast music.

**Comment by benborges** [comment]
thanks for answering so fast, well i wanted to download my brothers production https://www.mixcloud.com/crazymwandishi/ i already did on soundcloud 
that's my profile : https://www.mixcloud.com/buzzworkers/ but i don't use it much, my stuff is self hosted at www.buzzwokers.com

**Comment by benborges** [comment]
what i wanted to scrapp was : https://www.mixcloud.com/markus-herrmann2/the-acid-mercenaries-hardware-live-act-elemental-on-pure-radio-28092013/  and https://www.mixcloud.com/markus-herrmann2/the-acid-mercenaries-bruksellive-br%C3%BCssel-belgien-26072014/

**Comment by Miserlou** [comment]
Hmm, looks like Mixcloud don't like providing streams directly:

"The audio streams are not available through the Mixcloud API. There are two reasons for this.

Firstly, we need to know what has been listened to so that we can report usage, pay royalties and provide features such as "Suggested Shows". Secondly, Mixcloud needs to pay the bills! We can't give away the audio for free outside of mixcloud.com simply because it costs us to host and stream the files and pay royalties. " https://www.mixcloud.com/developers/

So, I guess the solution is probably to pull the audio stream location out of the embeddable player (ex http://api.mixcloud.com/spartacus/party-time/embed-html/ ) but it has a JS packer. Maybe it's encrypted in the 'playInfo' key?

Honestly this is going to be a fun puzzle but I'm too swamped to deal with directly right now. I'll report back if I ever get this sorted, hopefully not too long. Willing to accept pull requests as well.

. Also, it's in m4a format and not mp3, looks like, so that's another step.

**Comment by Miserlou** [comment]
Can't believe it's been March, really let this one slip.

Anyway, 0.18.0 has basic Mixcloud support. Extremely crude, but terse and without dependencies.
Support for more artists to come in 0.18.x+
Artist pages should land in 0.19.0
