### ISSUE TITLE
[Suggestion] Corrected tags for remixed or reposted tracks

### ISSUE THREAD

**Issue by justinglavin** [Miserlou/SoundScrape#55]
I listen to a lot of EDM music where a lot of the tracks are remixed by other artists. When these tracks are posted on Soundcloud, they're usually posted by the remixer, with the original artist & track title put in the title. 

Here's an example: https://soundcloud.com/samfeldt/years-years-shine-sam-feldt-remix-1

The result is a track tagged like such:

Artist: Sam Feldt
Track: Years & Years - Shine (Sam Feldt Remix)

A flag which would automatically correct this tagging would be awesome. The process should be static for most cases, scrape the original artist (before the - in the title), place that as the Artist and remove it from the title. 

Result:

Artist: Years & Years
Track: Shine (Sam Feldt Remix)

**Comment by Miserlou** [comment]
I've thought about this before, as a lot of times if you scrape a label's page, the songs are in format

Artist Name - Song Title (Blah Blah Remix)

and the ID3 will end up being

Artist: Label Name
Song: Artist Name - Song Title (Blah Blah Remix)

However, since there isn't really any consistency in title labeling, I'm not going to add this feature in as it's just going to be a huge headache to maintain.

Good idea though, thanks for writing.
