### ISSUE TITLE
Soundscrape doesn't download to current directory

### ISSUE THREAD

**Issue by philsalman** [Miserlou/SoundScrape#76]
After running this command `soundscrape https://soundcloud.com/troyboi/likes`, it runs like normal, no errors, but i can't find the tracks in my current directory. Is there a special directory that these tracks are being downloaded to?

**Comment by Miserlou** [comment]
Do you see a 'TroyBoi' directory?

**Comment by philsalman** [comment]
no, i actually used my own soundcloud account but dont seeany directories with my username

**Comment by tyhallcsu** [comment]
Try this command:

soundscrape troyboi -l

Flag -l downloads likes.

**Comment by philsalman** [comment]
@tyhallcsu same issue. Just an FYI, Im using Mac OS X Yosemite.

**Comment by tyhallcsu** [comment]
command:

pip install --upgrade soundscrape

^^ Make sure you have the newest version. 

And soundscrape doesn't download to a folder without the -f flag. otherwise, it downloads mp3's to the current working directory. 

soundscrape troyboi -l -f

^ will download troyboi's likes to the folder "TroyBoi"

**Comment by philsalman** [comment]
After reinstalling and updating soundscrape, everything is now working normally. Thanks
